### ISSUE TITLE
Upgrade version to get latest changes

### ISSUE THREAD

**Issue by can3p** [nakkaya/clodiuno#11]
Hi!

Thank you for your library and for your projects, because they are almost the single source of information regarding arduino and clojure.
I'm trying to add custom SYSEX commands in order to control the motorshield on the arduino and only pass high level commands to it (I'm using AF_motor library and I'm not sure if it's possible to reimplement it's functionality with simple analogWrite etc.)

I tried to receive the debug information from the arduino passing :msg-callback parameter with no luck. What I noticed is that the support of :msg-callback was added long after the last version was released, so probably the version of library I got with the lein deps simply does not contain this functionality.

Could you please upgrage the version of library, so that everyone can benefit from latest features?

**Comment by nakkaya** [comment]
I've just pushed the latest version.
