### ISSUE TITLE
NoSuchPortException with /dev/ttyUSB0

### ISSUE THREAD

**Issue by samrat** [nakkaya/clodiuno#7]
My board(Duemilanove with Atmega328) is mounted at /dev/ttyUSB0 and I'm getting a `NoSuchPortException` when I try

``` clojure
(arduino :firmata "/dev/USB0")
```

I'm not sure why this is happening. On the IDE, Serial Port is set to /dev/USB0 too and serial monitoring works fine in the IDE.

**Comment by nakkaya** [comment]
Sorry for the late reply. Guess Github stopped sending emails for issues. You can manually add it using,

```
(System/setProperty "gnu.io.rxtx.SerialPorts" "/path/to/your/port")
```

**Comment by samrat** [comment]
Sorry to bring this issue up again but this still isn't working for me. I'm still getting a NoSuchPortException.

**Comment by nakkaya** [comment]
Have you tried starting the repl/app as root? It may be a group/permission
problem.

**Comment by samrat** [comment]
Strangely while running `lein repl`(I usually use nrepl.el), I get

`check_group_uucp(): error testing lock file creation Error details:Permission deniedcheck_lock_status: No permission to create lock file.
please see: How can I use Lock Files with rxtx? in INSTALL`

both while running as root and as a normal user.

**Comment by samrat** [comment]
Just to be sure, I am in the uucp group.

**Comment by samrat** [comment]
I tried a workaround as described here: https://aur.archlinux.org/packages/arduino/ by hugueschabot and clodiuno seems to find my port but it hangs up when I do `(def board (arduino :firmata "/dev/ttyUSB0"))`.

**Comment by nakkaya** [comment]
Sorry about the late reply, I was at the protests. arduino fn returns
after firmata reports its version.

Can you comment out the while loop that waits for firmata to report the

## version and see if it works.

Nurullah Akkaya
http://nakkaya.com

**Comment by samrat** [comment]
Thanks, now its working for me.
